// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDW-Z6hJLOFoWQYo27EjOGJ_AEetw6RjvI',
    appId: '1:456457190973:web:01e7a7dab201eb7010f454',
    messagingSenderId: '456457190973',
    projectId: 'ecommerce-d5704',
    authDomain: 'ecommerce-d5704.firebaseapp.com',
    storageBucket: 'ecommerce-d5704.appspot.com',
    measurementId: 'G-7KX8YGTVD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHnwsDifwyjfD5aMOytn1D6SdJjWa1ozw',
    appId: '1:456457190973:android:40ac0186e755242b10f454',
    messagingSenderId: '456457190973',
    projectId: 'ecommerce-d5704',
    storageBucket: 'ecommerce-d5704.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPK3qGOed2AcfzR99hJzqs4Ch0K6DVRoM',
    appId: '1:456457190973:ios:d0cea7286207cbd810f454',
    messagingSenderId: '456457190973',
    projectId: 'ecommerce-d5704',
    storageBucket: 'ecommerce-d5704.appspot.com',
    iosBundleId: 'com.example.ecommerceapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPK3qGOed2AcfzR99hJzqs4Ch0K6DVRoM',
    appId: '1:456457190973:ios:d0cea7286207cbd810f454',
    messagingSenderId: '456457190973',
    projectId: 'ecommerce-d5704',
    storageBucket: 'ecommerce-d5704.appspot.com',
    iosBundleId: 'com.example.ecommerceapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDW-Z6hJLOFoWQYo27EjOGJ_AEetw6RjvI',
    appId: '1:456457190973:web:d0093ff6c685183810f454',
    messagingSenderId: '456457190973',
    projectId: 'ecommerce-d5704',
    authDomain: 'ecommerce-d5704.firebaseapp.com',
    storageBucket: 'ecommerce-d5704.appspot.com',
    measurementId: 'G-97QPC1VKY0',
  );
}
